# fly.toml app configuration file generated for lpc-product-creation-hidden-waterfall-5032 on 2024-10-22T17:27:46-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lpc-product-creation-hidden-waterfall-5032'
primary_region = 'sjc'

[build]

[env]
  PORT = '3000'
  SCOPES = 'read_orders,read_products,write_products'
  SHOPIFY_API_KEY = '6f1296c99bc07317bd7d904a9749bee4'
  SHOPIFY_APP_URL = 'https://lpc-product-creation.fly.dev'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
